apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodefront-deployment
  namespace: deployment
  labels:
    app: nodefront
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodefront
  template:
    metadata:
      labels:
        app: nodefront
    spec:
      containers:
      - name: nodefront
        image: vmahecha07/nodefront:latest
        ports:
        - containerPort: 3030
        