apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodefront-deployment
  labels:
    app: nodefront
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodefront
  template:
    metadata:
      labels:
        app: nodefront
    spec:
      containers:
      - name: nodefront
        image: vmahecha07/nodefront:latest
        ports:
        - containerPort: 3030
        env:

        - name: BACKEND_URL

          value: "10.233.51.211:3000"
        