apiVersion: v1
kind: Service
metadata:
  name: nodefront-service
  labels:
    app: nodefront
spec:
  type: NodePort
  selector:
    app: nodefront
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
      nodePort: 30007